### ISSUE TITLE
Change graphs to Cytoscape

### ISSUE THREAD

**Issue by andersonjonathan** [olale/Eiffel-Visualization#3]
Change the graphs to using [Cytoscape](http://js.cytoscape.org/) instead of dagre.

First testversion without any styling and with the flow downwards instead of left to right:  https://github.com/olale/Eiffel-Visualization/tree/03c06aa62c3f75bc773afd3c7d31d713cca34305

Pros:
* It is faster, about 0,5 seconds to render 20 graphs compared to 4-5 seconds for dagre
* It is actively maintained (https://github.com/cytoscape/cytoscape.js)
* Easy to change layout algorithm.
* Possible to store positions of nodes in database for even quicker access.

Cons:
* Some work is needed to style the nodes and edges, change the data structure etc.

**Comment by andersonjonathan** [comment]
If you think that the current layout is preferable (i think the layout in dagre is better), it is possible t use the dagre layout with Cytoscape and then store the positions on generation of the graphs instead in that way it should be as fast as Cytoscape but have a better layout. It also leaves it easy to change layout at a later point if the support for dagre is dropped.

**Comment by olale** [comment]
I think that sounds like a good idea. I tried to run the /cytoscape version of the app, but I can't seem to generate any graphs at all. It is listed that 5 of 5 graph instances are rendered, but I see nothing on the screen and no errors in the log. See attached screenshot.

<img width="962" alt="skarmavbild 2017-01-20 kl 07 11 29" src="https://cloud.githubusercontent.com/assets/3219537/22138237/e93d8d40-dedf-11e6-8024-0aa3c68f874d.png">

**Comment by andersonjonathan** [comment]
You need to run "node generate_graphs.js example1", or using example2 if that's where you imported the data, again since I modified the stored structure.

**Comment by olale** [comment]
Ok, now I see them. Great job making it faster! I say go with cytoscape, if it helps in rendering that much faster.
